name: Continuous Deployment

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      
      - name: Build Docker image for deployment
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: false
          tags: interview-webapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy application (mocked)
        run: |
          echo "🚀 Starting deployment to production..."
          echo "📦 Deploying Docker image: interview-webapp:latest"
          
          # Mock deployment - in real scenario this would be:
          # - Push to ECR registry
          # - Deploy to ECS
          # - Run smoke tests
          
          docker run -d --name production-app -p 3000:3000 interview-webapp:latest
          
          echo "⏳ Waiting for application to start..."
          sleep 10
          
          echo "✅ Deployment completed successfully!"

  post-deployment-verification:
    name: Post-Deployment Verification
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Health check verification
        run: |
          echo "🔍 Starting post-deployment verification..."
          
          # Wait for application to be ready
          sleep 15
          
          echo "🏥 Testing health endpoint..."
          if curl -f http://localhost:3000/health; then
            echo "✅ Health check passed!"
          else
            echo "❌ Health check failed!"
            exit 1
          fi
          
          echo "🌍 Testing main endpoint..."
          if curl -f http://localhost:3000/; then
            echo "✅ Application verification completed successfully!"
          else
            echo "❌ Main endpoint check failed!"
            exit 1
          fi

      - name: Cleanup on verification failure
        if: failure()
        run: |
          echo "🧹 Cleaning up failed deployment..."
          docker stop production-app || true
          docker rm production-app || true

  notify-failure:
    name: Notify Deployment Failure
    runs-on: ubuntu-latest
    needs: [deploy, post-deployment-verification]
    if: failure()
    steps:
      - name: Send failure notification
        run: |
          echo "🚨 DEPLOYMENT FAILED!"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          echo "Deploy result: ${{ needs.deploy.result }}"
          echo "Verification result: ${{ needs.post-deployment-verification.result }}"
          echo "Action required: Check workflow logs and fix deployment issue."

  cleanup:
    name: Cleanup Resources
    runs-on: ubuntu-latest
    needs: [deploy, post-deployment-verification]
    if: always()
    
    steps:
      - name: Clean up deployment resources
        run: |
          echo "🧹 Cleaning up deployment resources..."
          
          # Stop and remove the container (this is just for the mock deployment)
          docker stop production-app || echo "Container was not running"
          docker rm production-app || echo "Container was already removed"
          
          echo "✅ Cleanup completed"