name: Master Workflow

on:
  push:
    branches:
      - master

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml

  continuous-deployment:
    name: Continuous Deployment
    uses: ./.github/workflows/cd.yml
    needs: continuous-integration
    if: success()