name: Pull Requests Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  test-and-build:
    name: Test and Build
    uses: ./.github/workflows/ci.yml

  ci-status:
    name: Validate CI Status
    runs-on: ubuntu-latest
    needs: test-and-build
    if: always()
    steps:
      - name: Check all jobs succeeded
        run: |
          if [ "${{ needs.test-and-build.result }}" != "success" ]; then
            echo "❌ Pipeline failed: One or more jobs did not complete successfully"
            echo "Test and Build job result: ${{ needs.test-and-build.result }}"
            exit 1
          else
            echo "✅ All pipeline steps completed successfully!"
          fi